server:
  port: 8080
kafka:
  topic:
    event: sparkmall_event_log_topic #
    start: sparkmall_start_log_topic #
spring:
  kafka:
    bootstrap-servers: hadoop101:9092,hadoop102:9092,hadoop103:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  elasticsearch:
    jest:
      uris: http://192.168.213.101:9200,http://192.168.213.102:9200,http://192.168.213.103:9200
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch-cluster
#      cluster-nodes: 192.168.213.101:9300
#      repositories:
#        enabled: true